# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=20, verbose_name='Паспорт')),
                ('driverclass', models.CharField(max_length=20, verbose_name='Класс')),
                ('experience', models.CharField(max_length=20, verbose_name='Опыт')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('payment', models.IntegerField(verbose_name='Зарплата')),
            ],
        ),
    ]
